### ISSUE TITLE
Placing symbols with keyboard shprtcut does not work if using a trackpad

### ISSUE THREAD

**Issue by 12345ieee** [spacechem-community-developers/SpaceChem-Community-Edition#11] opened 2019-07-24 17:09 UTC
There is a report here: https://www.reddit.com/r/spacechem/comments/ccdmbg/trackpad_shortcut_bug_fix/ , but I already knew of this.

I can reproduce it easily on Windows, but not on Linux.

**Comment by csaboka** [comment] 2019-09-06 11:09
I can reproduce this. Placing symbols while holding the corresponding hotkey doesn't work, neither when tapping the trackpad nor when clicking the left button.

(Lenovo ThinkPad X1, Windows 10 Enterprise build 17763)

**Comment by csaboka** [comment] 2020-02-01 14:53
Looks like this isn't an issue with the game at all. The mouse down and mouse up events don't even reach the game in the first place, at least with the touchpad I can test with.

Apparently some touchpad events are ignored by the driver while you're typing, to prevent issues where your palm accidentally touches the pad while using the keyboard. Lenovo calls this PalmCheck, it may have a different name for other vendors. Holding down a hotkey for a symbol looks like typing as far as the driver is concerned, so it disables clicks in an effort to help you. SpaceChem can't do anything about it since it doesn't even see the event. I can reproduce the same behavior (clicks not working while a key is held down) with other apps.

There is nothing we can do about this as far as I can tell, so I'm closing this ticket. We can reopen if someone reports this issue only in SpaceChem (i.e. other apps detect the clicks while a key is being held down), assuming that the reporter is willing to run some debug builds for us.

**Closed by csaboka** 2020-02-01 14:53 UTC

**Comment by csaboka** [comment] 2020-02-01 15:26
For what it's worth, I can also reproduce the workaround suggested in the original Reddit post. Pressing Ctrl or Alt while holding down a key seems to disengage PalmCheck, as does clicking while holding Shift. Once you do either of those, clicking works until you release the original symbol hotkey. I can reproduce the same behavior in Paint, so it doesn't seem to be related to the game.

I guess different vendors may have different heuristics in their touchpad code, so it all depends on your vendor and/or OS.
