### ISSUE TITLE
Automatically select previously loaded solution after a game restart

### ISSUE THREAD

**Issue by rexkix** [spacechem-community-developers/SpaceChem-Community-Edition#30] opened 2020-06-14 12:35 UTC
Instead of selecting the Default solution, select the previously loaded solution after a game restart.

**Comment by csaboka** [comment] 2020-06-14 15:26
The problem is, I don't have a place to save which was the last loaded solution. I'm already doing some ugly hacks to the database to store multiple solutions at all, so saving the last loaded solution felt like overkill. It is remembered in memory, though, since that was easy to implement.

**Comment by csaboka** [comment] 2020-09-19 14:33
This will be part of the next CE release.

**Closed** 2020-10-06 06:17 UTC
