### ISSUE TITLE
Cannot exit level editor safely with several fusion/fission lasers enabled.

### ISSUE THREAD

**Issue by RandomPanda0** [spacechem-community-developers/SpaceChem-Community-Edition#24] opened 2020-05-12 01:17 UTC
When trialing ideas for a new level, I found that it is impossible to exit the testing area in the editor and reenter it without the game prompting me about a changed number of components, despite no change having taking place.  This seems to occur only when a CE-only amount of components are added.

Steps taken:
- Create puzzle, edit puzzle definition
- Set a component to an CE-only amount (e.g. Sensors to 2)
- Press "Save and Play"
- Exit test area
- Press "Save and Play" or "Save and Exit"

Taking either variant of the last steps results in a prompt showing up, despite no changes to he puzzle definition.  This seems to mostly be a minor bug, but there you go!

**Comment by csaboka** [comment] 2020-05-12 05:37
I can reproduce this. I'll take a closer look today or tomorrow.

**Comment by csaboka** [comment] 2020-05-12 06:59
Looks like this is more serious than what's reported. The custom sensor count isn't actually saved. (The same goes for fusion, fission and quantum tunnel features.) It _looks like_ it's saved because the in-memory version is used until you exit and restart the game.

I haven't noticed the issue because it's only present in the release build. I've only tested this in the debug build, and everything works as expected there.

The fix seems to be simple, so I'll probably be able to release a bugfix version during the weekend.

**Comment by csaboka** [comment] 2020-05-12 17:03
This should be fixed in the next release. Thank you for reporting the issue!

**Closed by csaboka** 2020-05-12 17:03 UTC
