### ISSUE TITLE
Typing `?` in a solution rename crashes the game

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#63] opened 2020-08-27 03:10 UTC
Reproducible on v6.0.1 Tournament week 9

**Comment by csaboka** [comment] 2020-08-27 05:37
Are you sure it's always crashing the game? We have a known issue where pressing the key next to the right Shift key triggers pasting. In the US layout, that key does forward slash and question mark. If you have a lot of data on your clipboard, the game will take a long time trying to insert it all, and will be unresponsive during that.

If it actually crashes (as opposed to becoming unresponsive), can you send the .zicrash file?

(Before sending the file, you probably want to remove your save file from it so you don't accidentally publish your week 9 solution. The .zicrash file is just a plain .zip file, and by deleting the "AppData/save" from it, you can remove all your puzzle solutions.)

**Comment by csaboka** [comment] 2020-08-28 20:51
Closing as a duplicate of an issue that's already fixed in source.

**Closed by csaboka** 2020-08-28 20:51 UTC
Labels: duplicate
