### ISSUE TITLE
 Incorrect size in full screen on a 4k monitor

### ISSUE THREAD

**Issue by MHBinky** [spacechem-community-developers/SpaceChem-Community-Edition#47] opened 2020-07-19 11:37 UTC
Booting up CE 6.0.1 fullscreen on a 4k monitor doesn't set the size right (it only fills a quarter of the screen), but disabling and reenabling fullscreen fixes it. This happens on every boot. I haven't had this problem with previous versions of the CE.

**Comment by csaboka** [comment] 2020-07-19 11:43
Can you please try this without the CE (i.e. opt out of all beta programs on Steam)? The CE doesn't change anything related to display, so it's very likely this is an issue with the base game.

If you can reproduce this without the CE, you should email Zachtronics with the issue report. Please also update this ticket so we can close this ticket if the issue isn't caused by the CE.

**Comment by MHBinky** [comment] 2020-07-19 11:50
Okay, I do get the same issue with the base game. Weird, it was displaying fine when I was copying the CE exe from github.

**Closed** 2020-07-19 11:50 UTC

**Comment by csaboka** [comment] 2020-07-19 11:53
The CE exe you can get from GitHub is based on v1015 of the base game. v1016 has changed the library used for displaying things, and CE 6.0.1 is based on that version.

**Comment by MHBinky** [comment] 2020-07-19 11:54
That makes sense.
