### ISSUE TITLE
Unused custom reactors show up in Free-Form production levels' JSON/map editor

### ISSUE THREAD

**Issue by zig1000** [spacechem-community-developers/SpaceChem-Community-Edition#15] opened 2019-11-26 00:51 UTC
The Free-Form production level editor ostensibly has toggles for whether each of the up to 4 custom reactors are used. However, these toggles appear to do nothing as all 4 custom reactors are always available in the editor and also bloat the level JSON code.

Not sure if this was a deliberate workaround of an implementation issue but it'd be nice to address.

**Comment by csaboka** [comment] 2019-11-26 05:58
This is working as intended. The four custom reactors are always supposed to be available in the reactor toolbar while editing the puzzle. The toggles are controlling whether the custom reactors are available while *playing* the puzzle. This allows the puzzle author to have a fixed custom reactor in the level without allowing the player to place more of that type, i.e. force the player to work with whatever is already placed. The built-in reactor types work the same way: they are always available in the puzzle editor, but only available for the player to place if the author toggled them on.

Yes, this also means that the custom reactor definitions are present in the JSON even if the puzzle author doesn't want to use them at all. It just doesn't seem to worth the extra effort to leave them out when unused. It's not like any of the communication channels where people share puzzles have a length limit that would prevent you from sharing the longer definition.

I'm closing this as "won't fix" for now, but please do comment here if I'm missing something, and I'll reopen if necessary.

**Closed by csaboka** 2019-11-26 05:58 UTC
Labels: wontfix
